### ISSUE TITLE
No "Apply" button on Graphics Settings. 

### ISSUE THREAD

**Issue by cloudedturtle** [UniverseProjects/voidspace-isssues#1]
There is no noticable method for changing the resolution of the game application on windows desktop. I can set the resolution, but I do not have any method of saving or applying the changes. 

**To Reproduce**
1. Go to the Options Menu
2. Select the Settings Button
3. Select the Graphics item 
4. Change Resolution from 1024x768 to something else
5. Close window, or change tabs
6. Returning Settings shows the 1024x768 setting again

 - Platform: Windows Desktop

**Comment by Emperorlou** [comment]
The settings are applied and saved immediately unless the individual setting has an apply button. The resolution specifically was an experiment and is not implemented (and will likely never be implemented). It will be removed in a subsequent update.
