### ISSUE TITLE
Experimentation may use the wrong item when selecting from a specific inventory

### ISSUE THREAD

**Issue by misterflippy** [UniverseProjects/voidspace-isssues#16]
**Describe the bug**
Studying an item from a specific inventory may not actually study the selected item. For example, studying "Electronics" from "Suit Storage A" may actually study "Copper Coil" instead.

**To Reproduce**
Prerequisites:
1. A boardable ship with items in the storage
2. Items in your suit storage

1. Board a ship and click the "Take Control" option (I boarded the "Old Ship" at the start of the game during the tutorial)
2. Click on the "Inventions" button to open the "Invention System" window
3. Click on the "Experiments" button to load the Experimentation section
4. Click on "Suit Storage A"
5. Select an item in the item list (Ex: I chose the 7th item, "5 Electronics"
6. Click "Study Item"
7. Immediately click the "Knowledge" button to switch to the Knowledge section
Result: "An experiment is in progress" notification displays with a knowledge name of "Copper". Upon completion, "Item Class: Copper" experience is gained
8. Click on the "Experiments" button to load the Experimentation section
9. In the "All" category, locate the 7th item in the list. (For me this is "7 Copper Coil")
10. In the "All" category, select the item previously selected in step #5 (For me this was "5 Electronics")
11. Click "Study Item"
12. Immediately click the "Knowledge" button to switch to the Knowledge section
Result: "An experiment is in progress" notification displays with a knowledge name of "Electronics". Upon completion, "Knowledge Class: Electrical Engineering" and "Item Class: Electronics" experience is gained.

Based on this, it seems like the experimentation system is using the item number/index on the wrong inventory list. That is, in my test, I selected the 7th item in my Suit Storage, but the game apparently selected the 7th item in the "All" list.

**Expected behavior**
I expect the item I select for an operation to be the one that the game actually uses for that operation.

**Screenshots**
![experimentation_all_storage](https://user-images.githubusercontent.com/50192591/73431384-8b553e00-42fd-11ea-93df-5bc4010db772.png)
![experimentation_suit_storage](https://user-images.githubusercontent.com/50192591/73431391-8e502e80-42fd-11ea-83b4-ca998fe9162b.png)

**Platform (please complete the following information):**
Desktop, Windows 10 64 bit
Client version 0.5.0-build3331

**Comment by Emperorlou** [comment]
Fixed!
