### ISSUE TITLE
Ideas directly in a category with subcategories are not viewable in the category

### ISSUE THREAD

**Issue by misterflippy** [UniverseProjects/voidspace-isssues#21]
**Describe the bug**
It's not possible to see ideas in categories that have subcategories -- clicking on the category expands or hides the subcategories and doesn't show ideas in that category. Example: "Build a Crude Asteroidal Storage Silo" is in category "Structures" but only shows up in category "All"

**To Reproduce**
Prerequisites:
1. Discovered idea "Build a Crude Asteroidal Storage Silo"

1. Click on the Invention System button in the toolbar to open the Invention System
2. Click on the Ideas button to switch to the Ideas section
3. Select category "All"
4. Scroll down in the Ideas: All section and find idea "Build a Crude Asteroidal Storage Silo"
5. Scroll down and click on the "Structures" category
Result: "Structures" category expands to display category "Modular Stations" but does not show idea "Build a Crude Asteroidal Storage Silo"

**Expected behavior**
One of:
1. Clicking on a category should expand that category *and* display all ideas directly under that category
-or-
2. Ideas should not be allowed to be directly in a category with subcategories and should instead be in a subcategory

**Platform (please complete the following information):**
Desktop: Windows 10 64 bit
Client version 0.5.0-build3344

**Comment by Emperorlou** [comment]
Should be good now. Reorganized it so everything is in a "leaf" category, and added some new categories.
