### ISSUE TITLE
Gas clouds spawned by venting engines result in broken clouds

### ISSUE THREAD

**Issue by BoeTaito** [UniverseProjects/voidspace-isssues#22]
**Bug Description:**

Gas clouds spawned by venting the gas stored inside engines creates are displayed as clouds made of "GasCloud" material, instead of the fluid you vented, and their info bar is blank when the cloud is viewed in the Inventions menu.

**To Reproduce:**

1. Locate an engine with fluid stored inside innately. (ie. not inside containers nested inside the engine)
2. Place the engine into your suit's inventory.
3. Take said engine to an area of space devoid of any gas clouds.
4. Exit any spaceship you used to travel to this location (if applicable)
5. Click on the engine inside your inventory.
6. Click on the "release fluid tank content" icon, it should look like a tap with green arrows pointing downwards at varying angles.

A gas cloud made of "GasCloud" should appear, unless there are hidden variables required to replicate this bug that I'm not aware of.

**Expected Behaviour:**

The gas cloud created using this method should not have a blank listing in the Inventions menu, and should be shown to be composed of the same fluid that was expelled when creating it. ie. if the engine contained hydrogen, then the gas cloud should display as a "Hydrogen Cloud"

**Screenshots**
![](https://cdn.discordapp.com/attachments/598899162968358943/675769166501773318/Untitled.png)

**Additional Notes:**

I've been told that these clouds made of "GasCloud" still yield the correct fluid if they're harvested, it's just how they're displayed that's an issue.

**Comment by Emperorlou** [comment]
I believe vented clouds are now the same as naturally generated clouds. I'll assume this is fixed and we can re-open if it's not.
