### ISSUE TITLE
Designing the crude transformer idea crashes the game

### ISSUE THREAD

**Issue by cloudedturtle** [UniverseProjects/voidspace-isssues#5]
**Describe the bug**
trying to start designing the crude transformer idea still instantly crashes the game though

**Additional context**
MildGrim: I wonder if its because the fabricator is used twice? I know I got it to work on another char but then I didn't use the fabricator at all, used the welder and cutter instead. Are you trying with double fabricators? Do you have more than one fabricator?
MildGrim: Putting the same fabricator in two spots might crash it

Maxion: oh, uh, huh, yeah it auto-selects my fabricator for both of the slots, that would explain it
Maxion: I had not scrolled far enough down the list to see that before
Maxion: but selecting my welder and cutter instead still crashed the game
Maxion: and happened again the next time I started the game and went straight for the welder and cutter
Maxion: (it still auto-selects the fabricator for both of them)

**Comment by Crokoking** [comment]
This issue has been fixed some time ago
