### ISSUE TITLE
Issues Mining Asteroids - Possibly Area Specific

### ISSUE THREAD

**Issue by cloudedturtle** [UniverseProjects/voidspace-isssues#6]
**Describe the bug**
Glorpian: I've got a bug where I can initiate mining but don't ever mine out anything:
* seems to affect all mining activity and pickup of loose items (asteroid, wreck, ECLS, starter wreck, ice asteroids, & ice chunk items, iron coil I made when "full" on inventory)
* spawning in a new character at the same place (through a friend in our mini community) found the new guy equally disabled suggesting it might be account or area-based
* as far as I can tell from a few veterans it sounds like you're aware of the issue and working on it
* possible temporary fix for others in same situation sounded to be flying away somewhat further and finding some unaffected asteroids/wrecks... (which would suggest area-based issue?)
* Edit 20:13 +1GMT: I should add that all error msgs for stuff like empty roids, or poor equipment trigger as normal

**Comment by cloudedturtle** [comment]
GiggleSquid: Can confirm. I'm havign the same issue
GiggleSquid: When anchored to an asteroid, checking contents removes start mining option
MildGrim: Yeah, but it's got some trick to it because that doesn't always happen across all chars/asteroids. Very strange one

**Comment by Emperorlou** [comment]
Seems to be working currently.
